# Generated by Django 2.0.2 on 2018-02-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='item_request_id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='relief_effort_id',
        ),
        migrations.RemoveField(
            model_name='orgadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='reliefeffort',
            name='org_admin_id',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='ItemRequest',
        ),
        migrations.DeleteModel(
            name='OrgAdmin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
