# Generated by Django 2.0.2 on 2018-02-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180218_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=100)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('relief_effort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ReliefEffort')),
            ],
        ),
    ]
